version: '3.4'

services:

  e1-pd-omni-gateway-mock:
    image: e1-pd/omni-gateway-mock:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile

  omni-gateway-mock:
    image: test4kids/omni-gateway-mock:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile.tc
